### ISSUE TITLE
Recurring job flood on init

### ISSUE THREAD

**Issue by lordnynex** [pintsized/lua-resty-qless#5]
Hello!

Is there a way (perhaps with resty-lock) to defer the first worker iteration loop in the init_by_lua phase? 

The reason I ask is recurring jobs are executed many times in the init phase. I can't seem to find a way to ensure the normal type of consistency at startup.

For example a simple recurring job without an offset like

``` lua
local _M = { }
_M.perform = function(job)
  local data = job.data or nil
  if not data then
    job:cancel()
    return nil
  end
  ngx.log(ngx.NOTICE, "Hello " .. tostring(data.hello))
  return true
end
return _M
```

will execute 100's of times per worker on init before finally 'normalizing' when one the job's return is updated in redis. I haven't tried yet but I think an offset may help, but if there was a "lock_initial" option that would simply pass while workers are initializing that would be great. 

Perhaps we could add something like `ngx.worker.exiting` into openresty that would return true until all workers have finished initialization?

**Comment by moteus** [comment]
I think problem is if you create recur job without `backlog` option then qless create one job per interval.
e.g. you create recur job with interval 60 sec. and wait 10 minutes before start worker. then when you start
worker there will be 10 avaliable jobs. You should be able see all this jobs in Web UI as `waiting` with jids like `<original jid>-NNN`. To limit number of such jobs you can use `backlog` option.
