### ISSUE TITLE
Jobs will nil return generate qless error

### ISSUE THREAD

**Issue by lordnynex** [pintsized/lua-resty-qless#6]
Hello,

Jobs which do not set a job outcome and fail to return bool generate a missing arg error when `job:fail` is called.

```
2016/01/15 13:23:47 [error] 4210#0: [lua] qless.lua:304: call(): ERR Error running script (call to f_7639fefe7d3a3bc713f2cbe9c5f63f68dc8d47d0): @user_script:573: user_script:573: Fail(): Arg "group" missing , context: ngx.timer                                     
2016/01/15 13:23:47 [error] 4210#0: [lua] job.lua:169: fail(): Could not fail job: ERR Error running script (call to f_7639fefe7d3a3bc713f2cbe9c5f63f68dc8d47d0): @user_script:573: user_script:573: Fail(): Arg "group" missing , context: ngx.timer
```

I'm not very familiar with qless redis script so I'm not sure what the group value actually represents, but is it possible to support a default value for this when fail is called?

**edit**

I think an obvious fix from my side would be wrapping the peform functions inner code block in a pcall to guarantee a return but I would assume this is a common enough situation to support a default value?

**Comment by pintsized** [comment]
Hi, sorry for the insanely slow response to this!

I've updated the develop branch to change the behaviour here. Jobs can just perform work without returning anything, and will be completed. If something goes wrong, they should return `nil, err_type, err_msg`, which will fail the job if you're using the built in worker.

Does this solve your issue?

https://github.com/pintsized/lua-resty-qless/tree/develop
