### ISSUE TITLE
Error when used with Redis 3.2.3

### ISSUE THREAD

**Issue by saucisson** [pintsized/lua-resty-qless#8]
When putting a job in queue and using Redis 3.2.3, an error occurs:

```
2016/09/15 23:43:19 [error] 2190#0: *1 [lua] qless.lua:305: put(): ERR Error running script (call to f_ad2dfd82189c92739c79fc30a2af6fd46c8a2793): @user_script:932: @user_script: 932: Lua redis() command arguments must be strings or integers , client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost:8080"
```

It disappears when switching to Redis 3.0.7.

This problem also seems to appear in https://github.com/AcademicWorks/resque-uniqueue/pull/4.

**Comment by pintsized** [comment]
Thanks for the report. Seems to be a PR for this on the qless-core repo: https://github.com/seomoz/qless-core/pull/64

So once that's merged I'll rebuild here.

**Comment by p0pr0ck5** [comment]
@pintsized looks like the above qless-core PR was merged?

**Comment by pintsized** [comment]
v0.09 should now work with Redis >= 3.2
